openapi: 3.0.2
info:
    title: Reemplazos API
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
paths:
    /reemplazos/upload:
        post:
            requestBody:
                content:
                    multipart/form-data: {}
                required: false
            responses:
                '200':
                    $ref: '#/components/responses/DatosExcelResponse'
            operationId: upload
components:
    schemas:
        DatosExcel:
            description: ''
            type: object
            properties:
                apellidoNombreReemplazante:
                    description: ''
                CUIL:
                    description: ''
                categoriaReemplazante:
                    description: ''
                intrumentoLegal:
                    description: ''
                periodoReemplazo:
                    description: ''
                diasAPagar:
                    description: ''
                guardias:
                    description: ''
                apellidoNombreTitular:
                    description: ''
                categoria:
                    description: ''
                periodoLicencia:
                    description: ''
                cantidadDiasLicencia:
                    description: ''
                tipoLicenciaTitular:
                    description: ''
    responses:
        DatosExcelResponse:
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/DatosExcel'
            description: ''
